# Generated by Django 5.0.3 on 2025-03-07 19:12

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [TrigramExtension()]
