# Generated by Django 5.0.3 on 2025-03-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_manually_add_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(default="Default description", max_length=2000),
        ),
    ]
