# Generated by Django 4.2.4 on 2023-11-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='want',
        ),
    ]
