# Generated by Django 4.2.4 on 2023-11-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_item_want'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='units_description',
            field=models.CharField(default='units', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='want',
            field=models.BooleanField(default=True),
        ),
    ]
