# Generated by Django 4.2.4 on 2023-09-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_org_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='org_contact_info',
            new_name='OrgContactInfo',
        ),
        migrations.RenameModel(
            old_name='org_info',
            new_name='OrgInfo',
        ),
        migrations.RenameModel(
            old_name='org_loc',
            new_name='OrgLocations',
        ),
    ]
