# Generated by Django 4.2.4 on 2023-09-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_customuser_non_profit_name_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgs_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('zip', models.SmallIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='orgs',
        ),
    ]
