# Generated by Django 4.2.4 on 2023-09-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_org_contact_info_orgcontactinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgLocations',
            new_name='OrgLocation',
        ),
    ]
