# Generated by Django 5.0 on 2024-01-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_orgcontactinfo_id_remove_orginfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='username',
            field=models.CharField(error_messages={'unique': 'Organization with this name already exists'}, max_length=100, unique=True, verbose_name='org name'),
        ),
    ]
