# Generated by Django 4.2.4 on 2023-09-18 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_orglocations_orglocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterModelOptions(
            name="org",
            options={"verbose_name": "Org", "verbose_name_plural": "Orgs"},
        ),
        migrations.AlterModelOptions(
            name="orgcontactinfo",
            options={
                "verbose_name": "OrgContactInfo",
                "verbose_name_plural": "OrgsContactInfo",
            },
        ),
        migrations.AlterModelOptions(
            name="orginfo",
            options={"verbose_name": "OrgInfo", "verbose_name_plural": "OrgsInfo"},
        ),
        migrations.AlterModelOptions(
            name="orglocation",
            options={
                "verbose_name": "OrgLocationInfo",
                "verbose_name_plural": "OrgsLocationInfo",
            },
        ),
        migrations.RemoveField(
            model_name="org",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="org",
            name="info",
        ),
        migrations.RemoveField(
            model_name="org",
            name="loc",
        ),
        migrations.RemoveField(
            model_name="org",
            name="non_profit_name",
        ),
        migrations.AddField(
            model_name="org",
            name="org_name",
            field=models.CharField(default="UN-NAMED-ORG", max_length=100),
        ),
        migrations.AddField(
            model_name="orgcontactinfo",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orginfo",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orglocation",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
