# Generated by Django 4.2.4 on 2023-09-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_orgcontactinfo_org_alter_orginfo_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='email',
        ),
        migrations.RemoveField(
            model_name='org',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='org',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(default='UN-NAMED-ORG', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orgcontactinfo',
            name='org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
