# Generated by Django 4.2.4 on 2023-10-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_org_org_name_alter_org_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(default='UN-NAMED-ORG', error_messages={'unique': 'Orginization with this name already exists'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
