# Generated by Django 4.2.4 on 2023-10-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_org_org_name_alter_orginfo_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(error_messages={'unique': 'Orginization with this name already exists'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orgcontactinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orgcontactinfo',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
