# Generated by Django 4.2.4 on 2023-10-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_item_org_alter_orgcontactinfo_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='DEFAULT_ITEM', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
