# Generated by Django 4.2.4 on 2023-11-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_org_managers_remove_org_org_name_org_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='DEFAULT_ITEM', max_length=100, unique=True),
        ),
    ]
