# Generated by Django 4.2.4 on 2023-11-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('org', 'item_name')},
        ),
    ]
